Select * From INFORMATION_SCHEMA.TABLES

Select * From INFORMATION_SCHEMA.COLUMNS
Where TABLE_NAME = 'gold.dim_customers'

Select Distinct country From [gold.dim_customers]

Select Distinct category, subcategory, product_name From [gold.dim_products]
Order by 1,2,3

Select MIN(order_date) As First_Order,
MAX(order_date) As Latest_order,
DATEDIFF(Year,MIN(order_date),MAX(order_date)) AS Time_span_years
FROM [gold.fact_sales]

-- Finding oldest and youngest customers
Select MIN(birthdate) AS Oldest_Customer,
DATEDIFF(year, MIN(birthdate), GETDATE()) AS Oldest_Age,
MAX(birthdate) AS Youngest_Customer,
DATEDIFF(Year, MAX(birthdate), GETDATE()) AS Youngest_Age
FROM [gold.dim_customers]

--Find Total sales
Select SUM(sales_amount) AS Total_Sales From [gold.fact_sales]

-- How many items are sold?
Select SUM(quantity) as Total_quantity_sold From [gold.fact_sales]

-- Find average selling price
Select AVG(price) As Avg_price From [gold.fact_sales]

-- Find the total number of orders
Select COUNT(order_number) AS Total_Orders From [gold.fact_sales]
Select COUNT(DISTINCT order_number) as Distinct_orders From [gold.fact_sales]

-- Total number of products
Select COUNT(product_name) As Total_Products From [gold.dim_products]
Select COUNT(DISTINCT product_name) As Total_Products From [gold.dim_products]

-- Total Number of Customers
Select COUNT(customer_key) as Total_customers FROM [gold.dim_customers]

-- Total number of customers that have placed an order
Select COUNT(DISTINCT customer_key) From [gold.fact_sales]

-- Generate a report that shows all Key metrics
Select 'Total Sales' as measure_name, SUM(sales_amount) AS measure_value From [gold.fact_sales]
union all
Select 'Total Quantity', SUM(quantity) From [gold.fact_sales]
union all
Select 'Avg_price', AVG(price) From [gold.fact_sales]
union all
Select 'Distinct_orders', COUNT(DISTINCT order_number) From [gold.fact_sales]
union all
Select 'Total_Products', COUNT(DISTINCT product_name) From [gold.dim_products]
union all
Select 'Total_customers', COUNT(customer_key) FROM [gold.dim_customers]
union all
Select 'Customers with orders', COUNT(DISTINCT customer_key) From [gold.fact_sales]

-- Find total customers by countries
Select country, Count(customer_key) as Total_customers From [gold.dim_customers]
group by country
order by Total_customers desc

-- Find total customers by gender
Select gender, Count(customer_key) as Total_customers From [gold.dim_customers]
group by gender
order by Total_customers desc

-- Find total products by category
Select category, COUNT(product_key) as Total_products From [gold.dim_products]
group by category
order by Total_products desc

-- Find average costs in each category
Select category, AVG(cost) as Avg_costs From [gold.dim_products]
Group by category
order by Avg_costs DESC;

-- Total Revenue genrated by each category
Select category, SUM(f.sales_amount) as Total_revenue From [gold.fact_sales] f
Left join [gold.dim_products] p on
f.product_key = p.product_key
group by p.category
order by Total_revenue desc

--Total revenue generated by each customer
Select c.customer_key, c.first_name, c.last_name, 
SUM(f.sales_amount) as Total_revenue From [gold.fact_sales] f
Left join [gold.dim_customers] c on
f.customer_key =c.customer_key
group by c.customer_key, c.first_name, c.last_name
order by Total_revenue desc;

-- Distribution of sold items across countries
Select c.country, SUM(f.quantity) AS Total_sold_items
From [gold.fact_sales] f
Left join [gold.dim_customers] c on
f.customer_key =c.customer_key
Group by c.country
order by Total_sold_items DESC;

-- 5 Products with the highest revenue
Select Top 5 
p.product_name, SUM(f.sales_amount) as Total_revenue From [gold.fact_sales] f
Left join [gold.dim_products] p on
f.product_key = p.product_key
group by p.product_name
order by Total_revenue desc

-- 5 worst performing products in terms of sales
Select TOP 5
p.product_name, SUM(f.sales_amount) as Total_revenue From [gold.fact_sales] f
Left join [gold.dim_products] p on
f.product_key = p.product_key
group by p.product_name
order by Total_revenue ASC

-- the 3 customers with the fewest orders placed
Select TOP 3
c.customer_key, c.first_name, c.last_name, 
COUNT(DISTINCT order_number) as Total_orders 
From [gold.fact_sales] f
Left join [gold.dim_customers] c on
f.customer_key =c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY Total_orders Asc;

-- Highest performing subcategory
Select subcategory, SUM(f.sales_amount) as Total_revenue From [gold.fact_sales] f
Left join [gold.dim_products] p on
f.product_key = p.product_key
group by p.subcategory
order by Total_revenue desc